### ISSUE TITLE
Paying invoices stops working after some time

### ISSUE THREAD

**Issue by sgeisler** [fiatjaf/kwh#1]
I'm using kwh with firefox 66.0.2 on NixOS with an autossh ssh tunnel to my spark wallet server. That means that the connection might be interrupted at times, but it'll be restored eventually. 

When I start a fresh firefox instance `lightning:<bolt11>` links, ´webln´ calls and pasting invoices works. But after some time (so far always with a connection interruption due to sleep in between) these features stop working. I can still list my transactions and generate invoices.

I attached two screenshots: one trying to pay a pasted invoice (blank area) and one after clicking a `lightning:` link and opening the menu to confirm the payment.

![2019-04-17-165049_3840x1080_scrot](https://user-images.githubusercontent.com/1876998/56297959-99045300-6131-11e9-8241-a2eba4c224aa.png)
![2019-04-17-164953_3840x1080_scrot](https://user-images.githubusercontent.com/1876998/56297958-99045300-6131-11e9-91d2-c239503ffc9c.png)

Thank you for building this great plugin, I was waiting for Joule c-lightning support for some time, this is a good alternative.

**Comment by fiatjaf** [comment]
It can't be anything related to connection interruption or sleep, as the extension calls the Spark server each time you open it or `webln` is triggered. Also I leave my browser opened for many days and I still see invoices working on https://lightning-roulette.com/, for example.

Just to clarify: you are unable to paste invoices in the "Paste bolt11 invoice here" textarea?

Please confirm to me the issue is not https://github.com/fiatjaf/kwh/issues/2 (I believe it's not, because that doesn't make it impossible for you to paste invoices in the blank "Pay" area).

**Comment by sgeisler** [comment]
Thank you so much, it's actually the same as #2 (I probably opened a new window after sleep but didn't think about that). 

I could still paste invoices, but clicking on pay just led to the blank "page" you can see in the picture and didn't pay.
