### ISSUE TITLE
Reduce clicks to confirm payment

### ISSUE THREAD

**Issue by sgeisler** [fiatjaf/kwh#4]
Currently if one clicks an invoice link there is the following workflow to confirm the payment:

1. click away (or wait for it to go away) the notification which is blocking the extension's button
2. open kwh
3. confirm payment

I think that's more interaction than necessary, for example one could get from 3 to 1 clicks using these two approaches:

1. add a button to the notification (seems possible according to the [API docs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/notifications/NotificationOptions#buttons), but I have no practical experience with JS/plugins)
2. remove the notification and open the kwh menu instead (I don't know if that's actually possible)

**Comment by fiatjaf** [comment]
Yeah, I would love that, and the code for it is already in place. The problem is: browsers don't support it.

What browser are you using?

**Your suggestion 2**: In the current [Chromium](https://chromium.woolyss.com/) the ability to open the popup menu programmatically is supported, so that is what you'll get with kWh today. On Firefox that isn't possible. On Chrome I believe you can get that behavior by [enabling the `Experimental Extension APIs` flag](https://github.com/mdn/browser-compat-data/pull/3675#issuecomment-482779328), which you can find on chrome://flags. If you do that and the extension popup is opened there won't be a notification at all, so that's the best thing.

**Your suggestion 1**: I tried, but this is currently impossible on Firefox. Firefox doesn't support buttons on notifications, and although every browser supports reacting to simple clicks on notifications -- which would be sufficient here -- [Firefox doesn't allow us to open the popup in reaction to that click](https://bugzilla.mozilla.org/show_bug.cgi?id=1402612). On Chrome it doesn't matter, because unless you turn on the aforementioned flag it won't be able to programmatically open the extension popup -- and if you do, there will be no notification anyway.

**Summary of the above**: Turn on the flag if you're on Chrome, pray if you're on Firefox.

---

Please let me know if the flag trick worked, so I could add it to the README.

**Comment by sgeisler** [comment]
I'm on Firefox, so praying it is I guess 😔 but I'll try it in chromium tomorrow.

Thank you for the long explanation, I'm not familiar with all the modern web stuff (and didn't expect it to be so broken, just feels like the old IE days all over again).

**Comment by k3tan172** [comment]
For what it's worth, whilst I find the 3 clicks excessive, it does make me stop and think, do I _really_ want to spend this?

**Comment by fiatjaf** [comment]
Well, I personally use Firefox too, but I use it most of the time in a half-window, so the notifications appear on the extreme right of the screen, while my extension button is roughly in the middle of the screen, so I don't have to click on the notification to make it disappear.

Please don't stop using Firefox because of this.

**Comment by fiatjaf** [comment]
Before anyone else mentions it: Joule opens a real popup window for payment confirmations instead of this extension popup thing kWh does. Apparently all browsers are fine with opening a real popup window, despite it being much more intrusive than the extension popup, which is odd.

I believe they copied it from Metamask, as it also does that and Joule explicitly says it's inspired by Metamask. Some years ago (when I was an Ethereum brainwashed know-nothing enthusiast and had Metamask installed despite never having used it) Metamask did something similar to what kWh does today (highlighted the extension icon and expected you to click on it) and I always missed it, that's why I added the notification to kWh.

Maybe people like the Joule popup. I however don't want to add a popup, I don't know why, but I don't like it. I'm open to being convinced, however.
